export enum UserRole {
  ADMIN = "ADMIN",
  TECNICO = "TECNICO",
  ATENDENTE = "ATENDENTE"
}

export enum OrderStatus {
  CRIADA = "CRIADA",
  AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO",
  APROVADA = "APROVADA",
  EM_REPARO = "EM_REPARO",
  TESTES_FINAIS = "TESTES_FINAIS",
  PRONTO_RETIRADA = "PRONTO_RETIRADA",
  FINALIZADA = "FINALIZADA",
  CANCELADA = "CANCELADA"
}

export enum OrderItemType {
  PECA = "PECA",
  SERVICO_MAO_DE_OBRA = "SERVICO_MAO_DE_OBRA"
}

export enum StockMovementType {
  ENTRADA = "ENTRADA",
  RESERVA = "RESERVA",
  CANCELAMENTO_RESERVA = "CANCELAMENTO_RESERVA",
  BAIXA_REPARO = "BAIXA_REPARO",
  PERDA_SUCATA = "PERDA_SUCATA",
  AJUSTE_INVENTARIO = "AJUSTE_INVENTARIO"
}
